[package]
name = "baza-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
baza = { path = "../" }
baza-api-s3 = { path = "../api/s3" }
structopt = "0.3.26"
tokio = "1.0"
tracing-subscriber = "0.2"