version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    labels: ["enhancement", "rust", "k::dependencies"]
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    labels: ["enhancement", "github_actions", "k::dependencies"]
    schedule:
      interval: daily
