[package]
name = "baza"
version = "0.1.0-dev"
edition = "2021"

[workspace]
members = [
    "api/s3",
    "e2e",
    "bin",
]

[dependencies]
async-fs = "1.5"
async-trait = "0.1.56"
derive_more = "0.99.17"
futures-lite = "1.12"
tracerr = "0.3"
tracing = "0.1.35"

