{{- range $name, $cred := dict "self" (.Values.image.credentials) "nginx" (.Values.nginx.image.credentials) }}
{{- if not (empty $cred) }}
{{- if not (and (eq $name "nginx") (not .Values.nginx.enabled)) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "baza.fullname" $ }}.{{ $name }}.registry
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "backend.chart" $ | quote }}
    app.kubernetes.io/name: {{ include "baza.name" $ | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{%s:{"auth":"%s"}}}` ($cred.registry | quote) (printf "%s:%s" $cred.username $cred.password | b64enc) | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}