kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s.env" (include "baza.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "baza.chart" . | quote }}
    app.kubernetes.io/name: {{ include "baza.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  BAZA_ACCESS_KEY: {{ .Values.conf.access_key | b64enc | quote }}
  BAZA_SECRET_KEY: {{ .Values.conf.secret_key | b64enc | quote }}
{{- if and .Values.nginx.enabled .Values.nginx.env }}
{{- range $name, $val := .Values.nginx.env }}
  {{ $name | quote }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
