kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "baza.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "baza.chart" . | quote }}
    app.kubernetes.io/name: {{ include "baza.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: api
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "baza.fullname" . | quote }}
  replicas: {{ .Values.statefulset.replicas | int }}
  revisionHistoryLimit: {{ .Values.statefulset.revisionHistoryLimit | int }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "baza.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "baza.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: api
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: baza
      {{- with .Values.statefulset.revision }}
        revision: {{ . | quote }}
      {{- end }}
      {{- with .Values.statefulset.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    {{- if or .Values.statefulset.nodeAffinity .Values.statefulset.podAffinity .Values.statefulset.podAntiAffinity }}
      affinity:
      {{- with .Values.statefulset.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.statefulset.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- if .Values.statefulset.podAntiAffinity }}
        podAntiAffinity:
        {{- if .Values.statefulset.podAntiAffinity.type }}
        {{- if eq .Values.statefulset.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .Values.statefulset.podAntiAffinity.topologyKey | quote }}
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "baza.name" . | quote }}
                  app.kubernetes.io/instance: {{ .Release.Name | quote }}
                  app.kubernetes.io/component: api
        {{- else if eq .Values.statefulset.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.statefulset.podAntiAffinity.weight | int64 }}
              podAffinityTerm:
                topologyKey: {{ .Values.statefulset.podAntiAffinity.topologyKey | quote }}
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "baza.name" . | quote }}
                    app.kubernetes.io/instance: {{ .Release.Name | quote }}
                    app.kubernetes.io/component: api
        {{- end }}
        {{- else }}
          {{- toYaml .Values.statefulset.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.statefulset.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: baza
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/baza", "-r /files", {{ printf "-l %s" .Values.conf.logLevel | quote }}]
          ports:
            - name: http
              containerPort: {{ .Values.conf.port | int }}
              protocol: TCP
          volumeMounts:
            - name: files
              mountPath: /files
        {{- with .Values.statefulset.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: files
